apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-secrets
  target:
    name: demo-secrets
    creationPolicy: Owner
  data:
    - secretKey: DEMO_MESSAGE
      remoteRef:
        key: demo-message
